flags: {}
extra-package-dbs: []
packages:
- '.'
- location: elm-compiler
  extra-dep: true
- location: elm-package
  extra-dep: true
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.9006030_ghc-7.10.3:
        url: http://ghcjs.tolysz.org/lts-6.30-9006030.tar.gz
        sha1: 2371e2ffe9e8781808b7a04313e6a0065b64ee51
extra-deps:
- Cabal-1.24.2.0
- HTTP-4000.2.23
- http-types-0.8.6
- optparse-applicative-0.11.0.2
compiler-check: match-exact
compiler: ghcjs-0.2.0.9006030_ghc-7.10.3
resolver: lts-6.30
